"""
exporter.py — TriplyAM file export
Supports: 3MF (default), STEP (via cadquery)
STL removed — insufficient metadata/IP protection.
Quality presets: low=0.5mm, medium=0.1mm, high=0.001mm
"""

import os
import struct
import numpy as np
from datetime import datetime

APP_NAME    = "TriplyAM"
APP_VERSION = "0.4.5"
APP_URL     = "https://github.com/Orville4th/TriplyAM"

QUALITY_PRESETS = {
    "Low":    0.5,
    "Medium": 0.1,
    "High":   0.001,
}


def export_stl(path, vertices, faces):
    """Internal STL writer — used by lattice pipeline (MeshLib temp files).
    NOT a user-facing export. Use export_3mf() for user exports."""
    import struct as _struct
    v = vertices.astype(np.float32)
    with open(path, 'wb') as f:
        f.write(b'\x00' * 80)
        f.write(_struct.pack('<I', len(faces)))
        for tri in faces:
            v0, v1, v2 = v[tri[0]], v[tri[1]], v[tri[2]]
            e1 = v1 - v0; e2 = v2 - v0
            n = np.cross(e1, e2)
            nl = np.linalg.norm(n)
            n = n / nl if nl > 1e-10 else np.array([0,0,1], dtype=np.float32)
            f.write(n.astype(np.float32).tobytes())
            f.write(v0.tobytes()); f.write(v1.tobytes()); f.write(v2.tobytes())
            f.write(b'\x00\x00')


def _build_metadata(agreed_to_terms=True):
    """Return standard metadata dict embedded in every export."""
    import socket
    try:
        hostname = socket.gethostname()
    except Exception:
        hostname = "unknown"
    try:
        ip = socket.gethostbyname(hostname)
    except Exception:
        ip = "unknown"
    return {
        "Generator":       f"{APP_NAME} v{APP_VERSION}",
        "GeneratorURL":    APP_URL,
        "ExportDate":      datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "License":         "Generated by TriplyAM open-source software. "
                           "No warranty. Use at your own risk. "
                           "See https://github.com/Orville4th/TriplyAM for terms.",
        "TermsAgreed":     "YES" if agreed_to_terms else "NOT_RECORDED",
        "GeneratedOnHost": hostname,
        "GeneratedOnIP":   ip,
        "Warning":         "This geometry has not been FEA-simulated or "
                           "structurally validated. The user assumes all "
                           "responsibility for testing before use.",
    }


def export_file(path, vertices, faces, quality="Medium", agreed_to_terms=True):
    ext = os.path.splitext(path)[1].lower()
    if ext == '.3mf':
        export_3mf(path, vertices, faces, agreed_to_terms=agreed_to_terms)
    elif ext in ('.step', '.stp'):
        export_step(path, vertices, faces, quality, agreed_to_terms=agreed_to_terms)
    else:
        raise ValueError(f"Unsupported export format: {ext}. TriplyAM exports 3MF and STEP only.")


def export_3mf(path, vertices, faces, name="TriplyAM Part", agreed_to_terms=True):
    """Write a 3MF archive with full TriplyAM metadata embedded."""
    import zipfile

    meta = _build_metadata(agreed_to_terms)

    # Build metadata XML block
    meta_lines = '\n'.join(
        f'  <metadata name="{k}">{v}</metadata>'
        for k, v in meta.items()
    )

    rels_content = """<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"
                Target="/3D/model.model" Id="rel0"/>
</Relationships>"""

    v_lines = '\n'.join(
        f'      <vertex x="{float(vertices[i,0]):.6f}" '
        f'y="{float(vertices[i,1]):.6f}" '
        f'z="{float(vertices[i,2]):.6f}"/>'
        for i in range(len(vertices))
    )
    f_lines = '\n'.join(
        f'      <triangle v1="{int(faces[i,0])}" '
        f'v2="{int(faces[i,1])}" '
        f'v3="{int(faces[i,2])}"/>'
        for i in range(len(faces))
    )

    model_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US"
       xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <metadata name="Title">{name}</metadata>
{meta_lines}
  <resources>
    <object id="1" type="model" name="{name}">
      <mesh>
        <vertices>
{v_lines}
        </vertices>
        <triangles>
{f_lines}
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="1"/>
  </build>
</model>"""

    with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('_rels/.rels', rels_content)
        zf.writestr('3D/model.model', model_content)
        zf.writestr('[Content_Types].xml',
            '<?xml version="1.0"?>'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
            '</Types>')


def export_step(path, vertices, faces, quality="Medium", agreed_to_terms=True):
    """
    Export STEP via cadquery BRep reconstruction.
    Falls back to faceted STEP if cadquery unavailable.
    """
    tol = QUALITY_PRESETS.get(quality, 0.1)
    meta = _build_metadata(agreed_to_terms)
    try:
        import cadquery as cq
        from OCC.Core.BRepBuilderAPI import (
            BRepBuilderAPI_MakePolygon,
            BRepBuilderAPI_MakeFace,
            BRepBuilderAPI_Sewing,
        )
        from OCC.Core.gp import gp_Pnt
        from OCC.Core.STEPControl import STEPControl_Writer, STEPControl_AsIs
        from OCC.Core.IFSelect import IFSelect_RetDone

        sewing = BRepBuilderAPI_Sewing(tol)
        v = vertices.astype(np.float64)
        for tri in faces:
            p0 = gp_Pnt(*v[tri[0]])
            p1 = gp_Pnt(*v[tri[1]])
            p2 = gp_Pnt(*v[tri[2]])
            wire = BRepBuilderAPI_MakePolygon(p0, p1, p2, True).Wire()
            face = BRepBuilderAPI_MakeFace(wire)
            if face.IsDone():
                sewing.Add(face.Face())
        sewing.Perform()
        sewn = sewing.SewedShape()
        writer = STEPControl_Writer()
        writer.Transfer(sewn, STEPControl_AsIs)
        status = writer.Write(path)
        if status != IFSelect_RetDone:
            raise RuntimeError("STEP write failed")
    except ImportError:
        _export_step_faceted(path, vertices, faces, meta)
    except Exception:
        _export_step_faceted(path, vertices, faces, meta)


def _export_step_faceted(path, vertices, faces, meta=None):
    """Faceted STEP fallback with TriplyAM metadata in file header."""
    if meta is None:
        meta = _build_metadata()
    desc  = meta.get("License", "TriplyAM Export")
    gen   = meta.get("Generator", APP_NAME)
    date  = meta.get("ExportDate", "")
    warn  = meta.get("Warning", "")

    lines = [
        "ISO-10303-21;",
        "HEADER;",
        f"FILE_DESCRIPTION(('{desc}'),'2;1');",
        f"FILE_NAME('','{date}',(''),(''),'{gen}','','');",
        f"/* {warn} */",
        "FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));",
        "ENDSEC;",
        "DATA;",
    ]
    idx = 1
    v = vertices.astype(np.float64)
    vert_ids = []
    for pt in v:
        lines.append(
            f"#{idx}=CARTESIAN_POINT('',({pt[0]:.6f},{pt[1]:.6f},{pt[2]:.6f}));"
        )
        vert_ids.append(idx); idx += 1
    for tri in faces:
        a, b, c = vert_ids[tri[0]], vert_ids[tri[1]], vert_ids[tri[2]]
        lines.append(f"#{idx}=FACE_BOUND('',#{a},#{b},#{c},.T.);"); idx += 1
    lines += ["ENDSEC;", "END-ISO-10303-21;"]
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
